### ISSUE TITLE
Feature request: 1.12.2 support like old versions epicguard

### ISSUE THREAD

**Issue by f3f5-dev** [4drian3d/EpicGuard#76]

**Comment by 4drian3d** [comment]
One of the reasons I followed the EpicGuard project is because of its exclusive support for higher versions in order to provide the best possible plugin with the best features provided by the latest versions of each platform. This will continue to be the case in later versions.
This also leads to deprecate the Waterfall (bungeecord) module for being a legacy platform with no evolution or future planning
